const SPOTIFY_ACCESS_TOKEN = "spotifyAccessToken";
const SPOTIFY_REFRESH_TOKEN = "spotifyRefreshToken";
const SPOTIFY_ACCESS_TOKEN_EXPIRY = "spotifyAccessTokenExpiry";
const SPOTIFY_LOGGED_IN_USER_ID = "spotifyLoggedInUserId";

export {
  SPOTIFY_ACCESS_TOKEN,
  SPOTIFY_REFRESH_TOKEN,
  SPOTIFY_ACCESS_TOKEN_EXPIRY,
  SPOTIFY_LOGGED_IN_USER_ID
}